apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 503015272051.dkr.ecr.us-east-1.amazonaws.com/my_db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
