apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: web-app
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 503015272051.dkr.ecr.us-east-1.amazonaws.com/my_app:latest
    env:
    - name: DBHOST
      value: "mysql-service.mysql.svc.cluster.local"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "blue"
    ports:
    - containerPort: 8080
