apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 503015272051.dkr.ecr.us-east-1.amazonaws.com/my_app:latest
        env:
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"
        ports:
        - containerPort: 8080
